# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"
 git:
    depth: 3
 env:
    global:
        - secure: "NWDJP5FOO4WUk9EE1FtYvlow+ixME3MGDVPyxwXAbcW+Q3XICgY8toZUiQOU/rWT9CO8WVSF6m0+lk1h6QTHXsr8F4JHplcBUcIxHUujQeeLeF03T8Fo0bVao/srC3YXwNRy53j+EwJbdFpISVZzttSMXXfPFWKqiq81hzyK5bKYwcc/lqsEEjHFSnfLFn5nB33RV76YNwemyzyN8QCDopKzz+ONYb0SBVYfbvcP2pLup6Y1WmNMehHKShXvADSMmOZQVT5oRb6rK4IcRhKclSWz4xqXLgne1Yzvk1EdsVtbkd9oSzwloX09wQFgUlryqkWGFZkCdvWayOEr4uF8It1cEhiZIHjkG3hQ4Vs/liBy3QZnW68H4XbeKtvJXkZcNp9+GG/dwUzZMgslmLv5bfihDQEiPD8tx7W3oz+TzCYLMZ9MM1VdWBaMNVoy8tgylRuR3vEvghwGyBPQYRcTVwCdHNr8z7VoGNKthclPtz83gMp09cdBZm71dEH/l4/bMxdeKwiMibDAzZXaE6dvs50D8Y+GqnX128PGgJYY9Ovnu6KjRXSFod3jpVCKPYVIau8cgDvWGbF8wiSiutyBRVwNpYzCx/PRZRiD6codVr+caA6gTW9W+2lJmERtg/k43O241ugMRA90s9IC5w+q51xWGCjvvv/+HUYnUQS5m5E="
 jobs:
     include:
        - name: build
          stage: build
          if: tag IS blank
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 


        - name: beta_build
          stage: build
          if: branch =~ (beta).*v[0-9]\..*
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 
          deploy:
            provider: releases
            api_key: MY_SECRET_ENV 
            file:
                -./.pioenvs/esp8285/firmware.bin
                -./.pioenvs/esp8285/spiffs.bin
            skip_cleanup: true
            prerelease: true
            on: 
                all_branches: true
                





#
# Template #2: The project is intended to be used as a library with examples.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# env:
#     - PLATFORMIO_CI_SRC=path/to/test/file.c
#     - PLATFORMIO_CI_SRC=examples/file.ino
#     - PLATFORMIO_CI_SRC=path/to/test/directory
#
# install:
#     - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio ci --lib="." --board=ID_1 --board=ID_2 --board=ID_N
