# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"
 git:
    depth: 3
 notifications:
    slack:
        secure: OAZTJvZPEMcF73JTe3MrrbduzU2tvSW8QRcR6YYCekE4TdfdUOWwufrEcXn31RyDu+VjWAYLXrcdl1sm0DhFK7kXB0l3hLAer39RdIr0B2BB2AqznVACSBRu2c567AbQG/mH6hQP/9CDBhG3J++9vMIxqN75WKj+nUTmWFhCf8lGSIijBV9Y4sg1PP7jmuXFl0ZT68BXYEPotYFilwOjb6s7pMK85pVmSfZTWj+9y2V3t3UhKKO2gSSsikHIxCTPgHA2C89f6Vr6YzT9iD3mjF6jgifqCuHbK0JX4UsInaqhUyS6mRPiF09/39lgNRgN2W/b0rmow+0XakNUaSJt76nnFFcICm0LqTP+dAL3SgyiK1SLaHjIRmtkf7NWejpD2+IAaeXqfAPvI81FfVANWO+exymSkc2BS3ahkq9IfBdeeJ3nO2ofzXLOVA3ScqlNpdpcD3bkslExng3AzHTh5vIX1maf89ykWkgWDt6osNBNF0dJbNHDcGDmoqgugzD3KTXDUD8hFZ98wZNziz1VMLwJljK3yYLMwv3GIxAF25YbE+fTEdcmmBFXTaE5K4KTtc0/LKVigO2AAog9tcPQ/ETsW3xLUBgKnjfBYl6jDgUTJ02kerW0LZyu4Woxc/9P5RRsOR4vlQhf8R5sEj+U4YuWOT6et03u67SzMxgu9g0=
        on_success: always
        on_failure: always
 jobs:
     include:
        - name: build
          stage: build
          if: branch = develop
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 


        - name: beta_build
          stage: build
          if: branch =~ (beta).*v[0-9]\..*
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 
          deploy:
            provider: releases
            file:
                - ./.pioenvs/esp8285/firmware.bin
                - ./.pioenvs/esp8285/spiffs.bin
            skip_cleanup: true
            prerelease: true
            api_key:
                secure: gx0NhBm/7UXo7Zql79z5yV3IMRc7VyL8kYyS9RXPWTo9ZOh3ZOIU706yvw83oxc8L6jxmKX/u9kJ102jNDM8Tg/o4qfdz4BBkyWBzamHyqjNX851WsjcIpPtFcyZc1bXRn8zPjXrtmNtgnUsvRVJjtSyyTeFVcqTdC243rKXwr7b8jy9YX4CuJnCy+UgZ1swHZRo1OyEWEYJe93tEBTQGN6WfrogBfQDPB8eLihheS6KUVGfBRMds7puCUMubBYlX/4tuyyB85I038ZGbqHEEGFvFa2y+zlOA5NS4FEhG+NV81kBIuF1Hj+KCSInxmjgWijVOtbsgZnIeFC+hKR5f8etvWStdtNAaxHpWu8qRS5mB5eVNzpvh1lgY3DxMLPHjdG20XB/inOIS7X0DO0rhHolGNgfmHOZyNf6IFy8VEHaz6NBJ7uNyfAVs536Qssk97vUXvNC/dbvxXogGUDeKnkQ/IgTT4Re0o4LrfGMs0WyXP+GlwCCiCMCArGHle/3x9CYSOgUgZ6F9mcogOJbv6rVZ5wChV0EbjoZJpjowUTXe5EHSE2tIllkybP0lEYZv745D+WlCGxjwczRPFoRL3BwKlFZ4q9a8mkmSJcdhZt0lQk0CouLH/qs/zFtBUuO+LgDf/pD7nbZDqBQyv9CNb+4f3oF5gJ2eIe1DYnk+4U=
            on: 
                all_branches: true
                repo: becothal/WLANThermo_nano_Software

        - name: release_build
          stage: build
          if: branch =~ v[0-9]\.[0-9]*
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 
          deploy:
            provider: releases
            file:
                - ./.pioenvs/esp8285/firmware.bin
                - ./.pioenvs/esp8285/spiffs.bin
            skip_cleanup: true
            prerelease: false
            api_key:
                secure: gx0NhBm/7UXo7Zql79z5yV3IMRc7VyL8kYyS9RXPWTo9ZOh3ZOIU706yvw83oxc8L6jxmKX/u9kJ102jNDM8Tg/o4qfdz4BBkyWBzamHyqjNX851WsjcIpPtFcyZc1bXRn8zPjXrtmNtgnUsvRVJjtSyyTeFVcqTdC243rKXwr7b8jy9YX4CuJnCy+UgZ1swHZRo1OyEWEYJe93tEBTQGN6WfrogBfQDPB8eLihheS6KUVGfBRMds7puCUMubBYlX/4tuyyB85I038ZGbqHEEGFvFa2y+zlOA5NS4FEhG+NV81kBIuF1Hj+KCSInxmjgWijVOtbsgZnIeFC+hKR5f8etvWStdtNAaxHpWu8qRS5mB5eVNzpvh1lgY3DxMLPHjdG20XB/inOIS7X0DO0rhHolGNgfmHOZyNf6IFy8VEHaz6NBJ7uNyfAVs536Qssk97vUXvNC/dbvxXogGUDeKnkQ/IgTT4Re0o4LrfGMs0WyXP+GlwCCiCMCArGHle/3x9CYSOgUgZ6F9mcogOJbv6rVZ5wChV0EbjoZJpjowUTXe5EHSE2tIllkybP0lEYZv745D+WlCGxjwczRPFoRL3BwKlFZ4q9a8mkmSJcdhZt0lQk0CouLH/qs/zFtBUuO+LgDf/pD7nbZDqBQyv9CNb+4f3oF5gJ2eIe1DYnk+4U=
            on: 
                all_branches: true
                repo: becothal/WLANThermo_nano_Software



#
# Template #2: The project is intended to be used as a library with examples.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# env:
#     - PLATFORMIO_CI_SRC=path/to/test/file.c
#     - PLATFORMIO_CI_SRC=examples/file.ino
#     - PLATFORMIO_CI_SRC=path/to/test/directory
#
# install:
#     - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio ci --lib="." --board=ID_1 --board=ID_2 --board=ID_N
