# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"
 git:
    depth: 3
 env:
    secure: t9dbyjQR6pIDsuXLBSno+x2mchiN51rvHuOOtb9svcJMBO+t19gOcmapcnPgICZ9psknLM+2RVDMc+gqqHm2eIyZ7dwc1r0nzkrBqFUhhhc2XGPMM9thL1etoU8PTiTj3Zom+088qi27M1w+eMQmO/RC3jdvXZ2UvCrxaqzEcnmAFmeyuw9Zqp3OjwpoNpme58kox9Sg+pQPAkZ3FdyTVFDWZtBtGF2tTvT6RBhsOPAuoa0tZ6RtvOB3Ke9nMaWR4rGh0K5aQ0Ym6t+X/uV04T4mPkdefKUj0tuB5zBktOQezq2Vs2W9RP3VtRMx7iw/DvCmlia+Ge4AZ1DhwoSAxCmkbkRCoYMusMthXlHPsyTY1LXMjEVi+M03w5agnLe0ZxYKqkO8Obad9qB2fJo7LPH0a2PVrqW5XruyyBR0hbXPC3z6ifSdw2dIZZ/vTq2T4LYkT+ZbnBKPMDu8Q2ILmNgVKPIIiGkmQbIBj3ArqGkg70UHTQUud2tl19ek8higJ9KMH7xEYTJb/zvQsUKME1maihRsMI/JJdLS2JIiOW2vbQKU1ujR0GGlveTSE38VBedeZuCGp5kXYUB6WAVBO/CHYxEi2iryB4Uecy2lmn11Bog3+K25jtDd38fGa/nZjmL5j5LaNNgyUJ1sMuGMD571Qf5vWiTD8UA9qiXd4do=
 jobs:
     include:
        - name: build
          stage: build
          if: tag IS blank
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 


        - name: beta_build
          stage: build
          if: branch =~ (beta).*v[0-9]\..*
          install:
              - pip install -U platformio
              - platformio update

          before_script:
              - gzip ./data_source/data/index.html
              - mv ./data_source/data/index.html.gz ./data/index.html.gz
              - mv ./data_source/data/nano.ttf ./data/nano.ttf 

          script:
              - platformio run && platformio run --target buildfs 
          deploy:
            provider: releases
            file:
                -./.pioenvs/esp8285/firmware.bin
                -./.pioenvs/esp8285/spiffs.bin
            skip_cleanup: true
            prerelease: true
            api_key: $API_KEY
            on: 
                all_branches: true
                





#
# Template #2: The project is intended to be used as a library with examples.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# env:
#     - PLATFORMIO_CI_SRC=path/to/test/file.c
#     - PLATFORMIO_CI_SRC=examples/file.ino
#     - PLATFORMIO_CI_SRC=path/to/test/directory
#
# install:
#     - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio ci --lib="." --board=ID_1 --board=ID_2 --board=ID_N
